name: TownyWars
version: 1.1.5
authors: [DanielRHarris, geostar1024]
main: net.minecraftcenter.townywars.TownyWars
depend: [Towny]
commands:
  twar:
    usage: No permission!
  twar neutral:
    permission: townywars.neutral
    usage: Syntax error! Perhaps you meant /twar neutral [nation]
